# Generated by Django 4.2.7 on 2023-12-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
