# Generated by Django 4.2.7 on 2023-12-15 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchased_cars', models.ManyToManyField(blank=True, to='car.car')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
